/**
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit';

var styles = css([".cds--shape-indicator,:host(cds-shape-indicator){color:var(--cds-text-secondary,#525252);display:flex;font-size:var(--cds-helper-text-01-font-size,.75rem);letter-spacing:var(--cds-helper-text-01-letter-spacing,.32px);line-height:var(--cds-helper-text-01-line-height,1.33333)}.cds--shape-indicator svg,:host(cds-shape-indicator) svg{align-self:center;margin-inline-end:.5rem}.cds--shape-indicator--14,:host(cds-shape-indicator[text-size=\"14\"]){font-size:var(--cds-body-compact-01-font-size,.875rem);font-weight:var(--cds-body-compact-01-font-weight,400);letter-spacing:var(--cds-body-compact-01-letter-spacing,.16px);line-height:var(--cds-body-compact-01-line-height,1.28572)}.cds--shape-indicator--failed,:host(cds-shape-indicator[kind=failed]) svg{fill:var(--cds-status-red,#da1e28)}.cds--shape-indicator--critical,:host(cds-shape-indicator[kind=critical]) svg{fill:var(--cds-status-red,#da1e28)}.cds--shape-indicator--high,:host(cds-shape-indicator[kind=high]) svg{fill:var(--cds-status-red,#da1e28)}.cds--shape-indicator--medium,:host(cds-shape-indicator[kind=medium]) svg{fill:var(--cds-status-orange,#ff832b)}.cds--shape-indicator--medium path:first-of-type,:host(cds-shape-indicator[kind=medium]) svg path:first-of-type{fill:var(--cds-status-orange-outline,#ba4e00)}.cds--shape-indicator--low,:host(cds-shape-indicator[kind=low]) svg{fill:var(--cds-status-yellow,#f1c21b)}.cds--shape-indicator--low path:nth-of-type(2),:host(cds-shape-indicator[kind=low]) svg path:nth-of-type(2){fill:var(--cds-status-yellow-outline,#8e6a00)}.cds--shape-indicator--cautious,:host(cds-shape-indicator[kind=cautious]) svg{fill:var(--cds-status-yellow,#f1c21b)}.cds--shape-indicator--cautious path:first-of-type,:host(cds-shape-indicator[kind=cautious]) svg path:first-of-type{fill:var(--cds-status-yellow-outline,#8e6a00)}.cds--shape-indicator--undefined,:host(cds-shape-indicator[kind=undefined]) svg{fill:var(--cds-status-purple,#8a3ffc)}.cds--shape-indicator--stable,:host(cds-shape-indicator[kind=stable]) svg{fill:var(--cds-status-green,#24a148)}.cds--shape-indicator--informative,:host(cds-shape-indicator[kind=informative]) svg{fill:var(--cds-status-blue,#0043ce)}.cds--shape-indicator--incomplete path:nth-of-type(2),:host(cds-shape-indicator[kind=incomplete]) svg path:nth-of-type(2){fill:var(--cds-status-blue,#0043ce)}.cds--shape-indicator--draft,:host(cds-shape-indicator[kind=draft]) svg{fill:var(--cds-status-gray,#6f6f6f)}"]);

export { styles as default };
//# sourceMappingURL=shape-indicator.scss.js.map
